version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.8
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 20s
      retries: 5
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my-network

  auth-generator:
    image: andrianovartemii/gm-test-task-auth-generator:latest
    ports:
      - "8082:8080"
    environment:
      AUTH_TOKEN_LIFETIME: ${AUTH_TOKEN_LIFETIME:-2}
    networks:
      - my-network

  gateway_service:
    build:
      context: ./Gateway Service
    restart: on-failure
    ports:
      - "8081:8081"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - my-network

  storage_service:
    build:
      context: ./Storage Service
    restart: on-failure
    ports:
      - "8085:8085"
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - my-network

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DATABASE:-database}
    networks:
      - my-network
    ports:
      - "5432:5432"
networks:
  my-network: